!autogenerated-by:     DAG-Edit version 1.419 rev 3
!saved-by:             gwg
!date:                 Fri Jul 08 08:18:09 BST 2005
!version: $Revision: 1.8 $
!type: % is_a is a
!type: < part_of part of
!type: * inverse_of inverse of
!type: £ disjoint_from disjoint from
!Gene_Ontology ; GO:0003673 
!cellular_component ; GO:0005575
  %cell ; GO:0005623
   <external encapsulating structure ; GO:0030312
    -cell envelope ; GO:0030313
    -cell wall ; GO:0005618
   <intracellular ; GO:0005622 ; synonym:protoplasm
    <chromosome ; GO:0005694
     %cytoplasmic chromosome ; GO:0000229 < cytoplasm ; GO:0005737
     %nuclear chromosome ; GO:0000228 < nucleus ; GO:0005634
    <cilium ; GO:0005929
    <cytoplasm ; GO:0005737
     <cytoplasmic chromosome ; GO:0000229 % chromosome ; GO:0005694
     <cytoplasmic membrane-bound vesicle ; GO:0016023
     <cytosol ; GO:0005829
     <endoplasmic reticulum ; GO:0005783 ; synonym:ER
     <endosome ; GO:0005768
     <Golgi apparatus ; GO:0005794 ; synonym:Golgi complex ; synonym:Golgi ribbon
     <lipid particle ; GO:0005811 ; synonym:lipid droplet
     <microtubule organizing center ; GO:0005815 ; synonym:MTOC ; synonym:microtubule organizing centre
     <mitochondrion ; GO:0005739
     <peroxisome ; GO:0005777, GO:0019818 ; synonym:peroxisome vesicle
     <plastid ; GO:0009536
     <ribosome ; GO:0005840
     <vacuole ; GO:0005773
      -lysosome ; GO:0005764
    <cytoskeleton ; GO:0005856
    <nucleus ; GO:0005634
     <nuclear chromosome ; GO:0000228 % chromosome ; GO:0005694
     <nuclear membrane ; GO:0005635, GO:0005636 ; synonym:nuclear envelope
     <nucleolus ; GO:0005730
     <nucleoplasm ; GO:0005654
    <thylakoid ; GO:0009579 ; synonym:photosynthetic membrane
   <plasma membrane ; GO:0005886 ; synonym:bacterial inner membrane ; synonym:cell membrane ; synonym:cytoplasmic membrane ; synonym:juxtamembrane ; synonym:plasmalemma
  %cellular component unknown ; GO:0008372
  %extracellular region ; GO:0005576 ; synonym:extracellular
   -extracellular matrix (sensu Metazoa) ; GO:0005578
   -extracellular space ; GO:0005615 ; synonym:intercellular space
  %unlocalized protein complex ; GO:0005941
