!autogenerated-by:     DAG-Edit version 1.419 rev 3
!saved-by:             gwg
!date:                 Fri Jul 08 08:18:09 BST 2005
!version: $Revision: 1.8 $
!type: % is_a is a
!type: < part_of part of
!type: * inverse_of inverse of
!type: £ disjoint_from disjoint from
!Gene_Ontology ; GO:0003673
!biological_process ; GO:0008150
  %behavior ; GO:0007610 ; synonym:behaviour
  %biological process unknown ; GO:0000004
  %cell communication ; GO:0007154
   <cell recognition ; GO:0008037
   %cell-cell signaling ; GO:0007267 ; synonym:cell-cell signalling
   %signal transduction ; GO:0007165
  %development ; GO:0007275
   <cell differentiation ; GO:0030154
   %embryonic development ; GO:0009790 ; synonym:embryogenesis
   %growth ; GO:0040007
    -cell growth ; GO:0016049 ; synonym:cell expansion ; synonym:cellular growth ; synonym:growth of cell < cell organization and biogenesis ; GO:0016043 < morphogenesis ; GO:0009653
   %morphogenesis ; GO:0009653
    -cell growth ; GO:0016049 ; synonym:cell expansion ; synonym:cellular growth ; synonym:growth of cell < cell organization and biogenesis ; GO:0016043 % growth ; GO:0040007
   <regulation of gene expression\, epigenetic ; GO:0040029
   %reproduction ; GO:0000003, GO:0019952
  %physiological process ; GO:0007582
   %cell cycle ; GO:0007049 ; synonym:cell-division cycle
   %cell homeostasis ; GO:0019725
   %cell organization and biogenesis ; GO:0016043
    <cell growth ; GO:0016049 ; synonym:cell expansion ; synonym:cellular growth ; synonym:growth of cell % growth ; GO:0040007 < morphogenesis ; GO:0009653
    %cytoplasm organization and biogenesis ; GO:0007028
    %organelle organization and biogenesis ; GO:0006996
     -cytoskeleton organization and biogenesis ; GO:0007010
     -mitochondrion organization and biogenesis ; GO:0007005
   %cell proliferation ; GO:0008283
   %death ; GO:0016265
    -cell death ; GO:0008219
   %metabolism ; GO:0008152 ; synonym:metabolic process
    %amino acid and derivative metabolism ; GO:0006519
    %biosynthesis ; GO:0009058 ; synonym:anabolism
     -protein biosynthesis ; GO:0006412, GO:0006416, GO:0006453 % protein metabolism ; GO:0019538
    %carbohydrate metabolism ; GO:0005975
    %catabolism ; GO:0009056
    %generation of precursor metabolites and energy ; GO:0006091 ; synonym:energy pathways
     -electron transport ; GO:0006118 ; synonym:electron transfer
    %lipid metabolism ; GO:0006629
    %nucleobase\, nucleoside\, nucleotide and nucleic acid metabolism ; GO:0006139
     %DNA metabolism ; GO:0006259
     %transcription ; GO:0006350 ; Reactome:74159
    %protein metabolism ; GO:0019538, GO:0006411 ; synonym:protein metabolism and modification
     %protein biosynthesis ; GO:0006412, GO:0006416, GO:0006453 % biosynthesis ; GO:0009058
     %protein modification ; GO:0006464
    %secondary metabolism ; GO:0019748
   %response to biotic stimulus ; GO:0009607
   %response to endogenous stimulus ; GO:0009719
   %response to external stimulus ; GO:0009605
    -response to abiotic stimulus ; GO:0009628
   %response to stress ; GO:0006950
   <transport ; GO:0006810
    %ion transport ; GO:0006811
    %protein transport ; GO:0015031, GO:0015831 ; synonym:enzyme transport
  %viral life cycle ; GO:0016032 ; synonym:viral infection ; synonym:viral replication cycle
