!autogenerated-by:     DAG-Edit version 1.419 rev 3
!saved-by:             gwg
!date:                 Fri Jul 08 08:18:09 BST 2005
!version: $Revision: 1.8 $
!type: % is_a is a
!type: < part_of part of
!type: * inverse_of inverse of
!type: £ disjoint_from disjoint from
!Gene_Ontology ; GO:0003673
!molecular_function ; GO:0003674
  %antioxidant activity ; GO:0016209
  %binding ; GO:0005488 ; synonym:ligand
   %calcium ion binding ; GO:0005509
   %carbohydrate binding ; GO:0030246
   %lipid binding ; GO:0008289
   %nucleic acid binding ; GO:0003676
    -DNA binding ; GO:0003677
     -chromatin binding ; GO:0003682
     -transcription factor activity ; GO:0003700, GO:0000130 % transcription regulator activity ; GO:0030528
    -RNA binding ; GO:0003723
    -translation factor activity\, nucleic acid binding ; GO:0008135 % translation regulator activity ; GO:0045182
   %nucleotide binding ; GO:0000166
   %oxygen binding ; GO:0019825 ; synonym:cytochrome P450
   %protein binding ; GO:0005515, GO:0045308 ; synonym:protein amino acid binding
    -cytoskeletal protein binding ; GO:0008092
     -actin binding ; GO:0003779
    -receptor binding ; GO:0005102 ; synonym:receptor ligand % signal transducer activity ; GO:0004871
  %catalytic activity ; GO:0003824 ; synonym:enzyme activity
   %hydrolase activity ; GO:0016787 ; EC:3.-.-.-
    -nuclease activity ; GO:0004518 ; EC:3.1.-.-
    -peptidase activity ; GO:0008233 ; EC:3.4.-.- ; synonym:hydrolase\, acting on peptide bonds ; synonym:peptide hydrolase ; synonym:protease
    -phosphoprotein phosphatase activity ; GO:0004721 ; EC:3.1.3.16 ; MetaCyc:3.1.3.16-RXN ; Reactome:113432 ; Reactome:113757 ; Reactome:115322 ; Reactome:115328 ; Reactome:115332 ; Reactome:117849 ; Reactome:117855 ; Reactome:117859 ; Reactome:117862 ; Reactome:120480 ; Reactome:120488 ; Reactome:122808 ; Reactome:122814 ; Reactome:122818 ; Reactome:124864 ; Reactome:124870 ; Reactome:69198 ; Reactome:69262 ; Reactome:69735 ; Reactome:69742 ; synonym:protein phosphatase activity
   %transferase activity ; GO:0016740 ; EC:2.-.-.-
    -kinase activity ; GO:0016301 ; Reactome:113431 ; Reactome:113433 ; Reactome:114246 ; Reactome:115027 ; Reactome:115715 ; Reactome:115932 ; Reactome:115944 ; Reactome:115947 ; Reactome:115951 ; Reactome:115974 ; Reactome:115991 ; Reactome:116605 ; Reactome:117491 ; Reactome:118310 ; Reactome:118568 ; Reactome:118583 ; Reactome:118586 ; Reactome:118589 ; Reactome:118596 ; Reactome:118617 ; Reactome:118965 ; Reactome:119356 ; Reactome:120179 ; Reactome:120930 ; Reactome:121183 ; Reactome:121192 ; Reactome:121216 ; Reactome:121239 ; Reactome:121274 ; Reactome:121543 ; Reactome:122577 ; Reactome:123125 ; Reactome:123301 ; Reactome:123309 ; Reactome:123312 ; Reactome:123316 ; Reactome:123331 ; Reactome:124636 ; Reactome:125197 ; Reactome:125408 ; Reactome:125423 ; Reactome:125426 ; Reactome:125441 ; Reactome:68385 ; Reactome:68401 ; Reactome:69194 ; Reactome:69222 ; Reactome:69246 ; Reactome:69254 ; Reactome:69603 ; Reactome:69607 ; Reactome:69716 ; Reactome:69904 ; Reactome:69913 ; Reactome:75047 ; Reactome:75051 ; Reactome:75052 ; Reactome:75053 ; Reactome:75054 ; Reactome:75225 ; Reactome:75371 ; Reactome:75808 ; Reactome:75819 ; Reactome:83536 ; synonym:phosphokinase
     -protein kinase activity ; GO:0004672 ; EC:2.7.1.37 ; MetaCyc:PROTEIN-KINASE-RXN
  %chaperone regulator activity ; GO:0030188
  %enzyme regulator activity ; GO:0030234 ; synonym:enzyme modulator
  %molecular function unknown ; GO:0005554
  %motor activity ; GO:0003774
  %nutrient reservoir activity ; GO:0045735
  %signal transducer activity ; GO:0004871
   %receptor activity ; GO:0004872
   %receptor binding ; GO:0005102 ; synonym:receptor ligand % protein binding ; GO:0005515
  %structural molecule activity ; GO:0005198
  %transcription regulator activity ; GO:0030528
   %transcription factor activity ; GO:0003700, GO:0000130 % DNA binding ; GO:0003677
  %translation regulator activity ; GO:0045182
   %translation factor activity\, nucleic acid binding ; GO:0008135 % nucleic acid binding ; GO:0003676
  %transporter activity ; GO:0005215
   %electron transporter activity ; GO:0005489
   %ion channel activity ; GO:0005216
   %neurotransmitter transporter activity ; GO:0005326
  %triplet codon-amino acid adaptor activity ; GO:0030533 ; synonym:tRNA ; synonym:transfer RNA
